/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'service-areas': ServiceArea;
    services: Service;
    locations: Location;
    'local-services': LocalService;
    sectors: Sector;
    'sector-services': SectorService;
    'case-studies': CaseStudy;
    posts: Post;
    categories: Category;
    authors: Author;
    media: Media;
    users: User;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'service-areas': ServiceAreasSelect<false> | ServiceAreasSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'local-services': LocalServicesSelect<false> | LocalServicesSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    'sector-services': SectorServicesSelect<false> | SectorServicesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('it' | 'en') | ('it' | 'en')[];
  globals: {
    company: Company;
  };
  globalsSelect: {
    company: CompanySelect<false> | CompanySelect<true>;
  };
  locale: 'it' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Le pagine principali di /servizi. Ognuna raccoglie i suoi sotto-servizi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas".
 */
export interface ServiceArea {
  id: string;
  title: string;
  /**
   * Es. 01
   */
  code?: string | null;
  /**
   * Titolo visibile in pagina, con la parola chiave principale. Se vuoto usa il titolo.
   */
  headline?: string | null;
  /**
   * Una riga, usata nelle card e negli elenchi.
   */
  short: string;
  /**
   * Paragrafo di 40–60 parole che risponde da solo alla domanda "cos'è / cosa fate / quanto costa". È il blocco che Google AI Overviews e ChatGPT citano.
   */
  answer?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Domande reali dei clienti. 5–8 per pagina servizio. Risposte dirette, 40–80 parole.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Parte finale dell'URL. Se vuoto viene generato dal titolo.
   */
  slug?: string | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Descrivi l'immagine: conta per accessibilità e SEO immagini.
   */
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  area: string | ServiceArea;
  /**
   * Titolo in pagina con la keyword principale, es. "Agenzia SEO locale a Rimini e Cattolica".
   */
  headline?: string | null;
  short: string;
  /**
   * Paragrafo di 40–60 parole che risponde da solo alla domanda "cos'è / cosa fate / quanto costa". È il blocco che Google AI Overviews e ChatGPT citano.
   */
  answer?: string | null;
  /**
   * Cosa non funziona oggi per il cliente tipo e perché.
   */
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * I passi con cui eroghiamo il servizio.
   */
  process?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Fascia indicativa: rassicura e qualifica i contatti. Lascia vuoto per non mostrarla.
   */
  pricing?: {
    from?: number | null;
    to?: number | null;
    unit?: ('project' | 'month') | null;
    note?: string | null;
  };
  /**
   * Domande reali dei clienti. 5–8 per pagina servizio. Risposte dirette, 40–80 parole.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  related?: (string | Service)[] | null;
  caseStudies?: (string | CaseStudy)[] | null;
  /**
   * Parte finale dell'URL. Se vuoto viene generato dal titolo.
   */
  slug?: string | null;
  order?: number | null;
  /**
   * Priorità editoriale.
   */
  wave?: ('1' | '2' | '3') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: string;
  /**
   * Es. CS·001
   */
  code?: string | null;
  industry?: string | null;
  title: string;
  /**
   * Es. +312% revenue YoY
   */
  metric?: string | null;
  excerpt?: string | null;
  levers?:
    | {
        lever: string;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  services?: (string | Service)[] | null;
  /**
   * Parte finale dell'URL. Se vuoto viene generato dal titolo.
   */
  slug?: string | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: string;
  name: string;
  /**
   * Es. RN, PU, MI, RM. SM per San Marino.
   */
  province: string;
  /**
   * Es. Emilia-Romagna, Lombardia
   */
  region?: string | null;
  /**
   * Es. Valconca, Riviera, Montefeltro
   */
  zone?: string | null;
  /**
   * Le città fuori zona non mostrano la distanza da Cattolica e compaiono nella sezione "In tutta Italia".
   */
  scope?: ('territorio' | 'italia') | null;
  headline?: string | null;
  short: string;
  /**
   * Paragrafo di 40–60 parole che risponde da solo alla domanda "cos'è / cosa fate / quanto costa". È il blocco che Google AI Overviews e ChatGPT citano.
   */
  answer?: string | null;
  economy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  challenges?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Domande reali dei clienti. 5–8 per pagina servizio. Risposte dirette, 40–80 parole.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  distanceKm?: number | null;
  travelMinutes?: number | null;
  geo?: {
    lat?: number | null;
    lng?: number | null;
  };
  highlights?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  sectors?: (string | Sector)[] | null;
  services?: (string | Service)[] | null;
  nearby?: (string | Location)[] | null;
  /**
   * Parte finale dell'URL. Se vuoto viene generato dal titolo.
   */
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: string;
  title: string;
  headline?: string | null;
  short: string;
  /**
   * Paragrafo di 40–60 parole che risponde da solo alla domanda "cos'è / cosa fate / quanto costa". È il blocco che Google AI Overviews e ChatGPT citano.
   */
  answer?: string | null;
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  process?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Domande reali dei clienti. 5–8 per pagina servizio. Risposte dirette, 40–80 parole.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  services?: (string | Service)[] | null;
  locations?: (string | Location)[] | null;
  caseStudies?: (string | CaseStudy)[] | null;
  /**
   * Parte finale dell'URL. Se vuoto viene generato dal titolo.
   */
  slug?: string | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "local-services".
 */
export interface LocalService {
  id: string;
  /**
   * Es. "Google Ads · Rimini"
   */
  title: string;
  location: string | Location;
  service: string | Service;
  headline: string;
  short: string;
  /**
   * Paragrafo di 40–60 parole che risponde da solo alla domanda "cos'è / cosa fate / quanto costa". È il blocco che Google AI Overviews e ChatGPT citano.
   */
  answer?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Domande reali dei clienti. 5–8 per pagina servizio. Risposte dirette, 40–80 parole.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-services".
 */
export interface SectorService {
  id: string;
  /**
   * Es. "Siti web · Hotel"
   */
  title: string;
  sector: string | Sector;
  service: string | Service;
  headline: string;
  short: string;
  /**
   * Paragrafo di 40–60 parole che risponde da solo alla domanda "cos'è / cosa fate / quanto costa". È il blocco che Google AI Overviews e ChatGPT citano.
   */
  answer?: string | null;
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  process?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Domande reali dei clienti. 5–8 per pagina servizio. Risposte dirette, 40–80 parole.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * 1–2 frasi per le card e i risultati di ricerca.
   */
  excerpt: string;
  cover?: (string | null) | Media;
  /**
   * Paragrafo di 40–60 parole che risponde da solo alla domanda "cos'è / cosa fate / quanto costa". È il blocco che Google AI Overviews e ChatGPT citano.
   */
  answer?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Domande reali dei clienti. 5–8 per pagina servizio. Risposte dirette, 40–80 parole.
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * L'articolo linka questi servizi e compare nelle loro pagine.
   */
  relatedServices?: (string | Service)[] | null;
  relatedPosts?: (string | Post)[] | null;
  /**
   * Parte finale dell'URL. Se vuoto viene generato dal titolo.
   */
  slug?: string | null;
  category?: (string | null) | Category;
  author?: (string | null) | Author;
  publishedAt?: string | null;
  /**
   * Calcolato in automatico se vuoto.
   */
  readingMinutes?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  description?: string | null;
  /**
   * Gli articoli della categoria compaiono nella pagina della macro-area.
   */
  area?: (string | null) | ServiceArea;
  /**
   * Parte finale dell'URL. Se vuoto viene generato dal titolo.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  role?: string | null;
  photo?: (string | null) | Media;
  bio?: string | null;
  /**
   * Es. 25Y
   */
  years?: string | null;
  yearsLabel?: string | null;
  vibe?: string | null;
  skills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  /**
   * LinkedIn ecc. Rafforzano l'entità autore per Google e le AI.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  color?: string | null;
  order?: number | null;
  /**
   * Parte finale dell'URL. Se vuoto viene generato dal titolo.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'service-areas';
          value: string | ServiceArea;
        } | null)
      | ({
          relationTo: 'services';
          value: string | Service;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'service-areas';
        value: string | ServiceArea;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'locations';
        value: string | Location;
      } | null)
    | ({
        relationTo: 'local-services';
        value: string | LocalService;
      } | null)
    | ({
        relationTo: 'sectors';
        value: string | Sector;
      } | null)
    | ({
        relationTo: 'sector-services';
        value: string | SectorService;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: string | CaseStudy;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-areas_select".
 */
export interface ServiceAreasSelect<T extends boolean = true> {
  title?: T;
  code?: T;
  headline?: T;
  short?: T;
  answer?: T;
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  slug?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  area?: T;
  headline?: T;
  short?: T;
  answer?: T;
  problem?: T;
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  body?: T;
  pricing?:
    | T
    | {
        from?: T;
        to?: T;
        unit?: T;
        note?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  related?: T;
  caseStudies?: T;
  slug?: T;
  order?: T;
  wave?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  province?: T;
  region?: T;
  zone?: T;
  scope?: T;
  headline?: T;
  short?: T;
  answer?: T;
  economy?: T;
  challenges?: T;
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  distanceKm?: T;
  travelMinutes?: T;
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  highlights?:
    | T
    | {
        item?: T;
        id?: T;
      };
  sectors?: T;
  services?: T;
  nearby?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "local-services_select".
 */
export interface LocalServicesSelect<T extends boolean = true> {
  title?: T;
  location?: T;
  service?: T;
  headline?: T;
  short?: T;
  answer?: T;
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  title?: T;
  headline?: T;
  short?: T;
  answer?: T;
  problem?: T;
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  services?: T;
  locations?: T;
  caseStudies?: T;
  slug?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sector-services_select".
 */
export interface SectorServicesSelect<T extends boolean = true> {
  title?: T;
  sector?: T;
  service?: T;
  headline?: T;
  short?: T;
  answer?: T;
  problem?: T;
  process?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  body?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  code?: T;
  industry?: T;
  title?: T;
  metric?: T;
  excerpt?: T;
  levers?:
    | T
    | {
        lever?: T;
        id?: T;
      };
  body?: T;
  services?: T;
  slug?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  cover?: T;
  answer?: T;
  content?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedServices?: T;
  relatedPosts?: T;
  slug?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  readingMinutes?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  area?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  years?: T;
  yearsLabel?: T;
  vibe?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  color?: T;
  order?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company".
 */
export interface Company {
  id: string;
  name: string;
  brand?: string | null;
  address?: string | null;
  cap?: string | null;
  city?: string | null;
  province?: string | null;
  piva?: string | null;
  email?: string | null;
  phone?: string | null;
  geo?: {
    lat?: number | null;
    lng?: number | null;
  };
  areaServed?: string[] | null;
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company_select".
 */
export interface CompanySelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  address?: T;
  cap?: T;
  city?: T;
  province?: T;
  piva?: T;
  email?: T;
  phone?: T;
  geo?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  areaServed?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: string | Post;
    } | null;
    global?: string | null;
    user?: {
      relationTo: 'users';
      value: string | User;
    } | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}